[package]
name = "modelica-fmi"
version = "0.0.9"
edition = "2024"

[dependencies]
askama = "0.16"
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
fmi-rs = { path = "../fmi-rs" }
sha2 = "0.10"
tempfile = "3"

[lints.clippy]
# Disallow explicit panicking mechanisms
unwrap_used = "warn"
expect_used = "warn"
panic = "warn"
todo = "warn"
unimplemented = "warn"
unreachable = "warn"
panic_in_result_fn = "warn"

# Disallow implicit panicking operations
# indexing_slicing = "deny"
# arithmetic_side_effects = "deny"

# Additional safety lints for fallible operations
# out_of_bounds_indexing = "deny"
# string_slice = "deny" # Slicing strings can panic if cut on non-UTF-8 boundaries
