on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-win64-binaries:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - run: cmake -S ./runtime -B ./runtime/win64 -G "Visual Studio 17 2022" -A x64
    - run: cmake --build ./runtime/win64 --config release --target install
    - uses: actions/upload-artifact@v4
      with:
       name: win64
       path: ./FMI/Resources/Library/win64/ModelicaFMI.dll
       if-no-files-found: error
  build-wheel:
    runs-on: ubuntu-22.04
    needs: [ build-win64-binaries ]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: win64
        path: .
    - run: tree
    - uses: actions/upload-artifact@v4
      with:
        name: Modelica-FMI
        path: .
        if-no-files-found: error
