on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-win64-binaries:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: recursive
    - run: cargo build --workspace --release
    - uses: actions/upload-artifact@v7
      with:
        name: win64
        path: |
          ./target/release/modelica-fmi.exe
          ./target/release/ModelicaFMI.dll
        if-no-files-found: error
  build-linux64-binaries:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: recursive
    - run: cargo build --workspace --release
    - uses: actions/upload-artifact@v7
      with:
        name: linux64
        path: |
          ./target/release/modelica-fmi
          ./target/release/libModelicaFMI.so
        if-no-files-found: error
  build-darwin64-binaries:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: recursive
    - run: cargo build --workspace --release
    - uses: actions/upload-artifact@v7
      with:
        name: darwin64
        path: |
          ./target/release/modelica-fmi
          ./target/release/libModelicaFMI.dylib
        if-no-files-found: error
  build-modelica-library:
    runs-on: ubuntu-22.04
    needs: [build-win64-binaries, build-linux64-binaries, build-darwin64-binaries]
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: recursive
    - uses: actions/download-artifact@v8
      with:
        name: win64
        path: ./FMI/Resources/Library/win64/
    - uses: actions/download-artifact@v8
      with:
        name: linux64
        path: ./FMI/Resources/Library/linux64/
    - uses: actions/download-artifact@v8
      with:
        name: darwin64
        path: ./FMI/Resources/Library/darwin64/
    - run: tree
    - uses: actions/upload-artifact@v7
      with:
        name: Modelica-FMI
        path: |
          FMI
          LICENSE
          README.md
        if-no-files-found: error
