on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-win64-binaries:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - run: cmake -S ./runtime -B ./runtime/win64 -G "Visual Studio 17 2022" -A x64
    - run: cmake --build ./runtime/win64 --config release --target install
